# Generated by Django 4.0.2 on 2022-02-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
