# Generated by Django 4.0.2 on 2022-03-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='category',
            field=models.CharField(blank=True, choices=[('coding', 'coding'), ('sports', 'sports'), ('entertainment', 'entertainment')], max_length=64, null=True),
        ),
    ]
