# Generated by Django 4.0.2 on 2022-02-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionListings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=64)),
                ('item_description', models.CharField(max_length=64)),
                ('item_startbid', models.DecimalField(decimal_places=2, max_digits=4)),
                ('item_url', models.URLField()),
                ('item_category', models.CharField(max_length=64)),
            ],
        ),
    ]
