# Generated by Django 4.0.2 on 2022-02-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auctionlistings_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='category',
            field=models.CharField(blank=True, choices=[('ANTIQUES', 'Antiques'), ('BOOKS', 'Books'), ('CARS', 'Cars'), ('CLOTHING', 'Clothing'), ('ELECTRONICS', 'Electronics'), ('RANDOM', 'Random')], max_length=64, null=True),
        ),
    ]
