# Generated by Django 4.0.2 on 2022-02-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auctionlistings_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
