# Generated by Django 4.0.2 on 2022-02-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_category_alter_auctionlistings_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='category',
            field=models.CharField(blank=True, choices=[('entertainment', 'entertainment'), ('sports', 'sports'), ('DNA', 'DNA'), ('motorcycles', 'motorcycles')], max_length=64, null=True),
        ),
    ]
