# Generated by Django 4.0.2 on 2022-03-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_comment_auctioncomments_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctioncomments',
            name='body',
            field=models.TextField(),
        ),
    ]
