# Generated by Django 4.0.2 on 2022-03-03 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auctioncomments_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctioncomments',
            name='add_comment',
        ),
    ]
