# Generated by Django 4.0.2 on 2022-03-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_auctioncomments_add_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
