# Generated by Django 4.0.2 on 2022-03-06 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auctionlistings_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionbids',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biduser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='category',
            field=models.CharField(blank=True, choices=[('Other', 'Other'), ('Electronics & Media', 'Electronics & Media'), ('Home & Garden', 'Home & Garden'), ('Clothing, Shoes & Accessories', 'Clothing, Shoes & Accessories'), ('Baby & Kids', 'Baby & Kids'), ('Vehicles', 'Vehicles'), ('Sports', 'Sports'), ('Collectibles', 'Collectibles')], max_length=64, null=True),
        ),
    ]
