# Generated by Django 4.0.2 on 2022-03-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_auctionbids_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctioncomments',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
