# Generated by Django 4.0.2 on 2022-03-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auctioncomments_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctioncomments',
            name='body',
            field=models.CharField(max_length=255),
        ),
    ]
